@startuml

node "Language Model" as langmodel {
    component "lang::sml::renderer"
    component "lang::sml::control"
}

"lang::sml::renderer" -[hidden]-> "lang::sml::control"

node "raven core (Rascal)" as rascal {
    component "Design Specification" as ds {

    }
    component "View Specification" as vs {

        }
    component "Change Listener" as listener

    component "Generator" as gen

}

interface "Scene Tree as JSON" as json

node "Java Server" as java {
component "Sender"
component "Receiver"
}

node "Godot" as godotBE {
component "Sender"
component "Receiver"
component "JSON Interpreter"
}


java -[hidden]-> rascal
json <.. godotBE :use
godotFE -[hidden]-> godotBE
ds ..> gen :use
 vs -u-> ds

godotBE --> displayui


vs ..> gen :use
gen --> json :produce
godotBE --> listener: communicate changes
listener --> gen :call on change

@enduml