@startuml
autonumber "<b>[000]"
actor       User        as user
participant "Rascal" as rascal
participant "(Java) \nServer" as server
participant "Godot \n Interpreter" as godot
participant "Godot \n Client" as client
== UI Initialization ==

user -> rascal : <<run(DSL Backend, \n View Specification, \n Design Specification)>>
activate rascal
rascal -> rascal: create JSON file
alt#pink #white Successful JSON Generation
    rascal -> server : <<start(jsonSpecification)>>
    server --> rascal: OK
    rascal -> godot : <<start(json)>>
    activate godot
    godot -> godot: <<generateSceneTree(json)>>
    godot -> client: Create UI
    deactivate godot
    activate client
else #pink Failure
    rascal --> user : Throw error (Invalid JSON)
end
activate server
server --> rascal: OK
deactivate rascal
deactivate server
== Program State Alteration ==
user -> client : <<click button>>
alt #Gold #White Alter runtime state
    client -> server : change detected \n (<<node information with callback>>)
    server -> rascal:  call callback \n with params (Evaluator)
    activate rascal
    rascal -> rascal: Execute callback, \n alter json specification
    rascal -> server : <<updateScene(json)>>
    deactivate rascal
    activate server
    server -> godot : send json
    activate godot
    godot -> godot: <<generateSceneTree(json)>>
    godot --> server: OK
    server -> rascal: call designated callback
    rascal --> server: send new json view
    server --> godot: send new json

    deactivate godot
    deactivate server

    godot -> client: updateScene
== Runtime State Alteration ==

@enduml
